# The metal3 chart is a parent chart that installs
# all of the other charts that a metal3 deployment needs,
# but doesn't actually deploy any services itself.

global:
  # IP on which the Ironic services will be exposed
  ironicIP: ""

  # whether to enable media server.
  enable_metal3_media_server: false

  # whether to enable dnsmasq on the provisioning network (for PXE boot)
  enable_dnsmasq: false

  # whether to enable PXE boot capability
  # NOTE: enable_dnsmasq must set to 'true' in order for this option to be effective.
  enable_pxe_boot: false

  # whether to enable Ironic services besides dnsmasq.
  # NOTE: enable_dnsmasq has precedence over this option. If enable_dnsmasq is set
  # to 'true' while enable_ironic is set to 'false', dnsmasq service will still be
  # enabled.
  enable_ironic: true

  # Host of the Ironic API
  ironicApiHost: ""
  # Host of the Ironic Inspector
  ironicInspectorHost: ""
  # Host of the Ironic Boot
  ironicBootHost: ""
  # Host of the Ironic Cache
  ironicCacheHost: ""

  # IP address of the router associated with the specified DHCP
  # address range
  dnsmasqDefaultRouter: ""

  # IP address of the dns server to be provided with DHCP
  # response
  dnsmasqDNSServer: ""

  # specify comma-delimited range of IP addresses the DHCP server will manage.
  # e.g 192.168.20.20,192.168.20.80
  dhcpRange: ""

  # Network interface on which provisioning network can be accessed
  provisioningInterface: ""

  # IP Address assigned to network interface on provisioning network
  provisioningIP: ""

  # Name for the MariaDB service
  databaseServiceName: metal3-mariadb

  # In a multi-node cluster use the node selector to ensure the pods
  # all run on the same host where the dnsmasqDNSServer and provisioningIP
  # and /opt/media exist. Uncomment the nodeSelector and update the
  # hostname accordingly.
  #nodeSelector:
    #kubernetes.io/hostname: "csrancher-n1"

#
# media service
#

# Override any settings for the metal3 media service here
metal3-media:
  # location where media files should be placed so that they are
  # available to the Ironic deployment services.
  mediaVolume:
    hostPath: /opt/media


#
# ironic service
#

# Override any settings for the metal3 ironic service here
# Ensure the storageClass is defined
metal3-ironic:
  service:
    type: LoadBalancer
  ingress:
    enabled: false

  persistence:
    ironic:
      # storageClass for the ironic shared volume
      storageClass: ""

#
# Database Service
#

# Override any settings for the metal3 mariadb service here
metal3-mariadb:
  # storageClass for the mysql datastore
  persistence:
    storageClass: ""
